
# base image
FROM node:14-alpine3.14

# Installs latest Chromium package.
RUN apk update && apk add --no-cache \
      udev \
      chromium \
      chromium-chromedriver \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn

ENV PATH="/app/node_modules/.bin:${PATH}"
ENV PATH="/usr/bin:${PATH}"
ENV chromedriver=/app/node_modules/.bin/chromedriver
ENV chromeDriver=/usr/bin/chromedriver

# set working directory
WORKDIR /app

# COPY all to root
COPY ./test/ui5-async.test.js ui5-async.test.js
COPY ./package.json package.json
COPY ./test/wdio-ui5-docker.conf.js wdio-ui5-docker.conf.js

RUN npm install

CMD npm run test:docker
